services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    environment:
      TZ: Europe/Oslo
    ports:
      - "1883:1883"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./data:/mosquitto/data
    networks:
      - homelab
    restart: unless-stopped

networks:
  homelab:
    external: true
